Add block woo loyal customer
studiopress/gcb-block-templates pull request #2
Opened 2021-01-04 01:14 UTC by RobStino

### How to test

1. 

### Documentation

### Suggested changelog entry

- 

### Notes

2021-01-06 15:43 UTC, cdils requested changes
Overall looks great! Just a few nitpicky formatting items to align with [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/.)

2021-01-06 15:43 UTC, cdils commented on blocks/woo-loyal-customer/block.css
> +    font-size:  44px;
Remove extra space

2021-01-06 15:43 UTC, cdils commented on blocks/woo-loyal-customer/block.css
> +    background-color:#ea533c;
Add space between `property: value`

2021-01-06 15:43 UTC, cdils commented on blocks/woo-loyal-customer/block.css
> +    color:#ffffff;
Add space between `property: value`

2021-01-06 15:43 UTC, cdils commented on blocks/woo-loyal-customer/block.php
> +    'numberposts' => 10, // one order is enough
- [ ] Align indentation
- [ ] Start inline comments with a Capital
- [ ] End inline comment with a `.`
```
    'numberposts' => 10, // One order is enough.
    'meta_key'       => '_customer_user',
```

2021-01-06 15:43 UTC, cdils commented on blocks/woo-loyal-customer/block.php
> +$min_previous_purchases = block_value('previous-purchases');
Put spaces on both sides of the opening and closing parentheses (here and elsewhere in this file)

`block_value( 'previous-purchases' )`

2021-01-06 15:43 UTC, cdils commented on blocks/woo-loyal-customer/block.php
> +// Minimum number of previous purchases to see the coupon
End comment with `.` (here and elsewhere in this file)

2021-01-06 15:43 UTC, cdils commented on blocks/woo-related-products/block.php
> +$product_tile_class = '';
Align indentation

```
$xyz123 = 'thing';
$x      = 'something';

```

2021-01-06 15:43 UTC, cdils commented on blocks/woo-related-products/block.php
> +        'tax_query' => array(
Align indentation

2021-01-06 15:43 UTC, cdils commented on blocks/woo-related-products/block.php
> +if ($the_query->have_posts()) {
Add space before and after parenthesis

2021-01-06 15:43 UTC, cdils commented on blocks/woo-related-products/block.php
> +                 echo $product->get_price(); //will give raw price
Comment formatting.

`// Will give raw price.`

2021-01-07 09:28 UTC, RobStino commented
Great review @cdils ! Thanks for taking the time to make those fixes!

2021-01-07 09:59 UTC, RobStino reviewed
These all look good!
Thanks again.
@cdils Can you approve the PR when you're able.

2021-01-07 16:22 UTC, cdils commented
No problem! Original review was just noting needed changes, but I went ahead and applied them. 

I'd recommend using [WP Coding Standards](https://github.com/WordPress/WordPress-Coding-Standards) moving forward since this is code we'll be distributing to the community.

2021-01-07 16:22 UTC, merged